version: '3.9'
services:
  nodejs-mongo-sample:
    build: .
    restart: on-failure
    ports:
      - '7777:7777'
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - default
    environment:
      - HOST=0.0.0.0
      - PORT=7777
      - MONGO_ADDRESS=mongodb://mongo:27017/mySampleDb

  mongo:
    image: mongo:8.0.4
    ports:
      - '27019:27017'
    volumes:
      - ./docker/data/mongo/db:/data/db
    networks:
      - default
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    driver: bridge